# Generated by Django 4.0.2 on 2022-09-30 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default='1')),
                ('point', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.grade')),
            ],
        ),
    ]
