<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-07-30 13:06
=======
# Generated by Django 4.0.2 on 2022-08-01 15:37
>>>>>>> c35045807438d838c3f0aa2095456e2d0c089f05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='HelloWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=225)),
=======
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('user_pswd1', models.CharField(max_length=10)),
                ('user_pswd2', models.CharField(max_length=10)),
>>>>>>> c35045807438d838c3f0aa2095456e2d0c089f05
            ],
        ),
    ]
