# Generated by Django 4.0.2 on 2023-01-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_remove_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='grade',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
