# Generated by Django 4.0.2 on 2022-11-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_alter_grade_grade_alter_user_grade'),
        ('accountapp', '0003_alter_user_grade'),
    ]

    operations = [
    ]
