<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-07-30 13:06
=======
# Generated by Django 4.0.2 on 2022-08-01 15:37
>>>>>>> c35045807438d838c3f0aa2095456e2d0c089f05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='profile/')),
                ('nickname', models.CharField(max_length=20, null=True, unique=True)),
                ('message', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
