# Generated by Django 4.0.2 on 2022-09-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0002_recomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReComment',
        ),
    ]
