# Generated by Django 4.0.2 on 2022-08-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='articlereceipt/'),
        ),
    ]
