# Generated by Django 4.0.2 on 2022-08-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='state',
            field=models.CharField(default='a', max_length=1),
        ),
    ]
