# Generated by Django 4.0.2 on 2022-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_campaign_amount_campaign_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
