# Generated by Django 4.0.2 on 2022-08-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_article_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='access_ip',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
