# Generated by Django 4.0.2 on 2022-08-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0004_article_access_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='count',
            new_name='counter',
        ),
        migrations.RemoveField(
            model_name='article',
            name='access_ip',
        ),
    ]
