# Generated by Django 4.0.2 on 2022-08-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0004_campaign_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
