# Generated by Django 4.0.2 on 2022-08-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0005_rename_count_article_counter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='counter',
            new_name='hit',
        ),
    ]
