# Generated by Django 4.0.2 on 2022-08-10 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articleapp', '0006_article_amount_campaign_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='Participants_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='Participants',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
