# Generated by Django 4.0.2 on 2022-08-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0007_campaign_participants_id_alter_campaign_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.CharField(default='a', max_length=1),
        ),
    ]
