# Generated by Django 4.0.2 on 2022-08-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0009_alter_campaign_participants_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='clothing',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='food',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='shelter',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
