# Generated by Django 4.0.2 on 2022-08-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0009_alter_campaign_participants_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='Participants_id',
            new_name='user',
        ),
    ]
