# Generated by Django 4.0.2 on 2022-08-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0010_campaign_clothing_campaign_food_campaign_shelter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='clothing',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='food',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='shelter',
        ),
        migrations.AddField(
            model_name='article',
            name='clothing',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='food',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='shelter',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
