# Generated by Django 4.0.2 on 2022-08-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0010_campaign_clothing_campaign_food_campaign_shelter'),
        ('articleapp', '0010_rename_participants_id_campaign_user'),
    ]

    operations = [
    ]
