# Generated by Django 4.0.2 on 2022-08-13 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0011_merge_20220811_0521'),
        ('articleapp', '0012_remove_article_clothing_remove_article_food_and_more'),
    ]

    operations = [
    ]
