# Generated by Django 4.0.2 on 2022-08-12 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articleapp', '0012_remove_article_clothing_remove_article_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='Participants',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='Participants_id',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='clothing',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='food',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='price',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='shelter',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='state',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='title',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='title_id',
        ),
        migrations.AddField(
            model_name='campaign',
            name='article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='articleapp.article'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='participants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.IntegerField(blank=True, default=0, null=True)),
                ('clothing', models.IntegerField(blank=True, default=0, null=True)),
                ('shelter', models.IntegerField(blank=True, default=0, null=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articleapp.campaign')),
            ],
        ),
    ]
