# Generated by Django 4.0.2 on 2022-08-13 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articleapp', '0013_merge_20220813_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='Participants',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='clothing',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='food',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='price',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='shelter',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='state',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='title',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='title_id',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='user',
        ),
        migrations.AddField(
            model_name='campaign',
            name='article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='articleapp.article'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='participants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.IntegerField(blank=True, default=0, null=True)),
                ('clothing', models.IntegerField(blank=True, default=0, null=True)),
                ('shelter', models.IntegerField(blank=True, default=0, null=True)),
                ('article', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricecategory', to='articleapp.article')),
            ],
        ),
    ]
