# Generated by Django 4.0.2 on 2022-08-12 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0013_remove_article_amount_remove_campaign_participants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.IntegerField(blank=True, default=0, null=True)),
                ('clothing', models.IntegerField(blank=True, default=0, null=True)),
                ('shelter', models.IntegerField(blank=True, default=0, null=True)),
                ('article', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricecategory', to='articleapp.article')),
            ],
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
