# Generated by Django 4.0.2 on 2022-08-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0014_rename_amount_article_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecategory',
            name='clothingPercent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pricecategory',
            name='foodPercent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pricecategory',
            name='shelterPercent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
