# Generated by Django 4.0.2 on 2022-08-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0014_pricecategory_delete_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='totalamount',
            field=models.IntegerField(default=0),
        ),
    ]
