# Generated by Django 4.0.2 on 2022-08-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0015_pricecategory_clothingpercent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricecategory',
            name='clothingPercent',
        ),
        migrations.RemoveField(
            model_name='pricecategory',
            name='foodPercent',
        ),
    ]
