# Generated by Django 4.0.2 on 2022-08-12 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0015_article_totalamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='totalamount',
            new_name='total_amount',
        ),
    ]
