# Generated by Django 4.0.2 on 2022-08-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0016_remove_pricecategory_clothingpercent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='state',
        ),
        migrations.RemoveField(
            model_name='pricecategory',
            name='shelterPercent',
        ),
        migrations.AddField(
            model_name='campaign',
            name='state',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='articleapp.article'),
        ),
    ]
