# Generated by Django 4.0.2 on 2022-08-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0017_alter_campaign_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='state',
        ),
        migrations.AddField(
            model_name='campaign',
            name='state',
            field=models.CharField(default='a', max_length=1),
        ),
    ]
