# Generated by Django 4.0.2 on 2022-08-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0018_remove_article_state_campaign_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='receipt',
            field=models.ImageField(null=True, upload_to='article/'),
        ),
    ]
