<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-07-30 13:06
=======
# Generated by Django 4.0.2 on 2022-08-01 15:37
>>>>>>> c35045807438d838c3f0aa2095456e2d0c089f05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
