# Generated by Django 4.0.2 on 2022-11-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society', models.TextField(max_length=50, null=True)),
                ('region', models.TextField(max_length=20, null=True)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
