# Generated by Django 4.0.2 on 2022-08-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
