# Generated by Django 4.0.2 on 2022-09-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='logo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='society',
            name='site',
            field=models.TextField(null=True),
        ),
    ]
